### ISSUE TITLE
4/27/2020 twice instead of 4/28/2020 in data_total.tsv

### ISSUE THREAD

**Issue by edomt** [raunakms/covid19nepal#1]
Hi @raunakms,

Many thanks for updating this dataset every day!
There seems to be a small issue in `data/data_total.tsv`: the date on lines 79 and 80, appears twice as 4/27/2020 (instead of 4/28/2020 the second time).

Edouard

**Comment by raunakms** [comment]
Thanks @edomt for pointing the error. I have now fixed it.
