### ISSUE TITLE
Data Outdated

### ISSUE THREAD

**Issue by yudhir** [raunakms/covid19nepal#2]
Since Our World in Data uses this , Better provide up to date data as People will link Nepal's Info in their papers and researches .

**Comment by yudhir** [comment]
@raunakms  This needs attention . There are BBC articles stuck with Old data on Nepal as of today .  https://www.bbc.com/news/world-asia-53420537

**Comment by raunakms** [comment]
Thanks for highlighting the issue. These data in my repo. were manually curated by myself and is certainly an laborious effort. The data were not updated due inconsistency of data format released by Nepal Govt. as well as I'm tremendously occupied with COVID related research works in US and in Nepal. Most of the API released by the Nepal Govt. has access control and thus cannot be automated. I'm not currently in Nepal and I'm a full time researcher working on COVID in US. I need some volunteer to continue this work. If you are willing to volunteer and spare some time to manually curate the data, I can certainly point you to the relevant resources.  Thanks

**Comment by yudhir** [comment]
Maybe Guys at covidnepal.org are interested and Automate the process for OurworldinData's need . Maintainers of the Project @jagatmachines
